name: Build & Deploy Storybook
on:
  push:
    branches: [dev]
    paths: ['dabeeo-react-ui/src/components/**']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: |
          yarn set version berry
          yarn install
          yarn run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: ./dabeeo-react-ui
