name: Build & Deploy Storybook
on: # 언제 실행?
  push:
    branches: dev # dev 브랜치
    paths: 'dabeeo-react-ui/src/components/**' # dabeeo-react-ui 아래 컴포넌트쪽 변경이 일어나는 경우?
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
    - name: Use repository source
      uses: actions/checkout@v3

    - name: Use node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
      working-directory: ./dabeeo-react-ui

    - name: Set PUBLIC_URL
      run: |
        PUBLIC_URL=$(echo $GITHUB_REPOSITORY | sed -r 's/^.+\/(.+)$/\/\1\//')
        echo PUBLIC_URL=$PUBLIC_URL > .env

    - name: Build Storybook
      run: |
        yarn run build-storybook
        pwd
        ls -la
        mkdir -p ./dist
        mv ./storybook-static ./dist/storybook
        ls -la
      working-directory: ./dabeeo-react-ui

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        working-directory: ./dabeeo-react-ui
